function M=Matrix3DRotation(alpha,beta,gamma,t)
% Matrix to rotate a point P around t by Euler's angles alpha, beta, gamma 
%  angles in degrees !
%-------------------------------------------------------------------------
T=[ 1, 0, 0,  t(1);...
    0, 1, 0,  t(2);...
    0, 0, 1,  t(3);...
    0, 0, 0,  t(4)];
TI=[1, 0, 0, -t(1);...
    0, 1, 0, -t(2);...
    0, 0, 1, -t(3);...
    0, 0, 0,  t(4)];
Rx=[1,     0,            0,       0;...
    0, cosd(alpha), -sind(alpha), 0;...
    0, sind(alpha),  cosd(alpha), 0;...
    0,     0,            0,       1];
%
Ry=[cosd(beta),  0, -sind(beta), 0;...
         0,      1,      0,      0;...
     sind(beta), 0,  cosd(beta), 0;...
         0,      0,      0,      1];
% 
Rz=[cosd(gamma), -sind(gamma), 0, 0;...
    sind(gamma),  cosd(gamma), 0, 0;...
        0,            0,       1, 0;...
        0,            0,       0, 1];
%M=T*Rx*Ry*Rz*TI;
% M=T*Rx*Rz*Ry*TI;
%M=T*Rz*Ry*Rx*TI;
% M=T*Rz*Rx*Ry*TI;
% M=T*Ry*Rz*Rx*TI;
M=T*Ry*Rx*Rz*TI;
end

